version: '3'
services:
  mySQL:
    image: mysql:5.7
    restart: unless-stopped
#    env_file:
#      - .env
    environment:
#      MYSQL_USER : root
      MYSQL_ROOT_PASSWORD : password
      MYSQL_DATABASE : db
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - net
  app:
    image: $IMAGE_NAME
    environment:
      DB_HOST: mySQL
      DB_PORT: 3306
      DB_NAME: db
      DB_USERNAME: root
      DB_PASSWORD: password
    ports:
      - "8089:8089"
    depends_on:
      - mySQL
    networks:
      - net

  prometheus:
    image: prom/prometheus:v2.47.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    depends_on:
      - node_exporter
    networks:
      - net

  grafana:
    image: grafana/grafana:10.0.5
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=adminpassword
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    networks:
      - net

  node_exporter:
    image: prom/node-exporter:v1.6.1
    ports:
      - '9100:9100'
    networks:
      - net

networks:
  net:
    driver: bridge
volumes:
  db: